apiVersion: apps/v1
kind: Deployment
metadata:
  name: codtech-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codtech
  template:
    metadata:
      labels:
        app: codtech
    spec:
      containers:
        - name: codtech-container
          image: nginx
          ports:
            - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: codtech-service
spec:
  type: NodePort
  selector:
    app: codtech
  ports:
    - port: 80
      targetPort: 80
